language: php

sudo: false

git:
  depth: 1

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

before_script:
  - composer install

script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then  travis_retry bash -x ./run-tests-with-coverage.sh; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then  travis_retry bash -x ./run-tests.sh; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then bash <(curl -s https://codecov.io/bash); fi
