language: php

sudo: false

git:
  depth: 1

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

before_script:
  - composer install

script:
  - travis_retry bash -x ./run-tests-with-coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
