language: php

git:
  depth: 1

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

cache:
  directories:
  - ./vendor

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-scripts --no-progress --optimize-autoloader --no-ansi --no-interaction --profile --no-plugins -vvv

script:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then  travis_retry ./vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then  travis_retry ./vendor/bin/phpunit; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -B $TRAVIS_BRANCH; fi
